### ISSUE TITLE
Bundle is included with installation instead of "Fast Follow"

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [jelte/be.khepri.play.assetdelivery.addressables#11] opened 2020-12-02 08:27 UTC
I created Addressable Group with audio files that take around 50MB. I want to be able to use Play Asset Delivery, with delivery mode "Fast Follow", so the bundle would be downloaded only after the app itself is installed. 
I followed your instruction for installation and configuration. I've added the scheme "Fast Follow" to Addressable Group, then I followed the 3 steps for the manual build process.
Now I have 2 problems:
1. The aab file is created, but it fails to sign it with error: "Signing failed: Failed to locate keystore file: mykeystore.keystore". I'm sure that my settings are fine in Unity Project Settings, regarding keystore file, pass, alias and alias password. For now, I just used apksigner to add my signature to the aab. Maybe you have any idea what might be the problem there.
2. I uploaded the aab file to the internal test in Google Play Store. When I'm downloading the app, because of the size, I can tell right away that the whole 50MB bundle is included in the installation, and not separated into a bundle, as I hoped. Any suggestion what possibly went wrong?

Thanks!

**Comment by jelte** [comment] 2020-12-02 13:49
1. Play Asset Delivery from google wraps the unity build process, so it should take whatever is set for the normal build process. I do know that if you've recently upgraded unity the configuration format changed. You may want to try reselecting the keystore and setting the pass, etc. in the Unity Project Settings.
To check if it is related to the Play Asset Delivery you could create the AAB with the normal build process, just to eliminate the cause.

2. for fast-follow the size of the asset pack will be included on the play store, so nothing wrong there.
```fast-follow asset packs are downloaded automatically as soon as the app is installed; the user does not have to open the app for fast-follow downloads to begin. These downloads do not prevent the user from entering the app. These packs contribute to the app size listed on the Google Play Store.```
source: https://developer.android.com/guide/app-bundle/asset-delivery

**Comment by a-l-e-x-d-s-9** [comment] 2020-12-03 06:50
Thanks for your response.
1. Creation of AAB with the normal build process works fine. Not sure what's the problem there with "Google > Build Android App Bundle", but it's not a critical problem because I can easily sign the AAB myself.
2. Thanks for correcting my false assumption regarding "fast-follow", I really appreciate it.
3. I've changed the delivery mode to "On Demand" for my addressable group. Cleaned the bundle build, followed your 3 steps for a manual build. Uploaded the AAB to internal test in Play Store. From the size of the app installation, seems that my addressable bundle is included with the app, and not delivered separably. Maybe I am missing something in a bundle configuration, here is how my inspector configured for the bundle:
![image](https://user-images.githubusercontent.com/6518064/100972740-f553fa80-3541-11eb-97a1-7d0a0cbd0047.png)

**Comment by jelte** [comment] 2020-12-04 00:02
1. Which version of Unity are you using? maybe something specifically changed, I've tested it with 2018 and 2019.
3. Which version of Addressables are you using ? I've only tested with the latest verified version (1.8.5)
3. Also see that you still need to set the Asset Provider and Asset Bundle Provider, so Addressables will load the bundles from Asset Packs.

**Comment by a-l-e-x-d-s-9** [comment] 2020-12-04 06:26
1. Unity 2019.4.15f1.
2. Addressables 1.16.13, and now upgraded to 1.16.15.
3. I've changed Asset Bundle Provider, is it fine?
![image](https://user-images.githubusercontent.com/6518064/101129182-cacd7480-3609-11eb-9186-2a644e10df96.png)
4. I've upgraded to Addressables 1.16.15, changed Asset Bundle Provider, cleaned, three steps build, uploaded AAB to internal test, same result as before.

**Comment by jelte** [comment] 2020-12-05 12:59
1. odd, this package doesn't do anything with the signing. I did have a quick look at the `Google Android App Bundle` package. They do seem to not use the build in to sign. Perhaps you can set some breakpoints or debug lines in `Library/PackageCache/com.google.android.appbundle@1.2.0/Editor/Scripts/Internal/BuildTools/ApkSigner.cs` on line 153, and further to see what is happening.

2. I will checkout out 1.16, but this may take as I need to setup a new test project.
3. That seems fine.

4. I think I found what is going wrong, seems a change in Addressables changed the structure of the build folder and now suffixes the build and load path with the build target in the default settings: https://github.com/jelte/be.khepri.play.assetdelivery.addressables/issues/12

**Comment by a-l-e-x-d-s-9** [comment] 2020-12-06 13:54
I've tested 1.0.0-rc2. Maybe I messed something up, but from what it looks like, the addressable bundle added twice, both into basic part of the AAB and also as on-demand package. 

This is how AAB looks for this version:
![image](https://user-images.githubusercontent.com/6518064/101280989-2e57cd80-37d5-11eb-8e39-adff4ae04546.png)

My AAB base was ~93MB before I added addressable group:
![image](https://user-images.githubusercontent.com/6518064/101281513-00c05380-37d8-11eb-8ac6-7028b38054c4.png)

To build I did do: 
1. Addressable Group > Build > Clean Build > All 
2. Addressable Group > Build > New Build > Default Build Script
3. Google > Create config for Addressables Groups
4. Google > Build Android App Bundle

Any suggestions?

**Comment by jelte** [comment] 2020-12-06 14:27
Looking into it, sorry I need to setup an entire new project to test with (just changed job ;)) and Google review is being slow. So my testing is a bit adhoc atm. Sorry for the inconvenience.

**Comment by jelte** [comment] 2020-12-06 15:18
Just pushed 1.0.0-rc3, which includes a fix where asset bundles are not being removed from the AssetStreaming direction when using the default config setup. as it didn't look into sub directories.

**Comment by a-l-e-x-d-s-9** [comment] 2020-12-07 06:58
Good luck with a new job!
I've tested 1.0.0-rc3, it looks that on-demand bundle is added as expected to assets pack in AAB, the initial app size not containing the bundle, and from internal test on google play store the bundle seems to be downloaded and working.
Thanks for your excellent work!

**Closed** 2020-12-07 09:56 UTC
Labels: bug
